### ISSUE TITLE
Using this library in ionic v2 framework running angular 2

### ISSUE THREAD

**Issue by vikramezhil** [adonespitogo/angular-base64-upload#102]
Hello, I am unable to set this library up in ionic framework running angular 2 as I am stuck on setting the below line of code.

`angular.module('myApp', ['naif.base64'])`

I believe for angular 2 the modules needs to be imported as a header and set in **app.model.ts file**. Any steps or guidance on having this run in angular 2 would be much appreciated.

Thanks,
Vikram Ezhil

**Comment by adonespitogo** [comment]
This module is for angular v1.x, not for v2.x
