### ISSUE TITLE
Uncaught Exception with oversized files

### ISSUE THREAD

**Issue by samtgarson** [adonespitogo/angular-base64-upload#11]
I get an exception `RangeError: Invalid string length` on the line 
```javascript
var base64 = btoa(e.target.result);
```

During testing I uploaded a PSD file which is over 400MB—obviously this is a ridiculous and largely unrealistic size of file but could we handle the error?

**Comment by adonespitogo** [comment]
I haven't had a chance to look into this yet. There's no way to catch the exception currently.
