### ISSUE TITLE
How can i upload multiple images ?

### ISSUE THREAD

**Issue by Nishchit14** [adonespitogo/angular-base64-upload#17]
Multiple images cant select by this library.

Is there any way to do this ?

**Comment by adonespitogo** [comment]
Yes, you can do it by adding multiple `<input type="file" ng-model="model1" base-sixty-four-input>` in the form:

```
<form>
  <input type="file" ng-model="model1" base-sixty-four-input>
  <input type="file" ng-model="model2" base-sixty-four-input>
</form>
```

But if you are referring to `multiple` attribute for input element. I would invalidate this question as it is already stated in the readme that it only supports single file selection (as of the moment).
