### ISSUE TITLE
Great works but problem with PHP

### ISSUE THREAD

**Issue by digitalxpIT** [adonespitogo/angular-base64-upload#18]
When I crop the image i put a button to upload with ng-click='uploadFile()' and in the controller i make this changes:

$scope.uploadFile = function(){
	//$scope.myCroppedImage is the name of img src
        
$http.post('/public/up64.php', $scope.myCroppedImage)
        .success(function(res){
          alert('View file '+res+'  ?');
          $window.location.assign(res);
        })
 }

But I receive error from PHP!

fopen(): Filename cannot be empty in .....on line 18
fwrite() expects parameter 1 to be resource, boolean given in ....line 19
 fclose() expects parameter 1 to be resource, boolean given in....line 20

I've to make changes on php files?!

**Comment by adonespitogo** [comment]
Sorry, I think this has nothing to do with the directive. The scope of this project is only to convert a file into base64-encoding and attaching it to your `ng-model`. In this case, the error is in your PHP script and not in the `base-sixty-four-input` directive.
