### ISSUE TITLE
Add a Data URI scheme format

### ISSUE THREAD

**Issue by kermit666** [adonespitogo/angular-base64-upload#21]
To be able to use the image in a roundtrip back on the UI in Angular, we need to write something like:

    <img data-ng-src="{{picture.dataURI}}"/>

where `dataURI` needs to be the [Data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) for the browser to render the image properly:

    picture.dataURI = "data:image/" + picture.filetype + ";base64," + picture.base64;

Having to manually type this out is a bit tiresome and it would be cool if there was e.g. a method like `picture.dataURI()` that we could call. It could maybe be added to the `fileObject` or as some sort of service. What do you think? I could try to prepare a pull request if you're interested.

**Comment by adonespitogo** [comment]
Yeah I think that would be cool. Would be good if we could do this for other file types like video, audio, etc. 
http://stackoverflow.com/questions/2270151/is-it-possible-to-use-data-uris-in-video-and-audio-tags
http://iandevlin.com/html5/data-uri/video.php

**Comment by adonespitogo** [comment]
We can make this functionality as a separate directive which sole purpose is to display base64-encoded files.

**Comment by kermit666** [comment]
I tried it with a new directive, but it couldn't find a good way to organise things without repeating code too much. I added it as a method for now with a TODO note about adding other file type schemes in the future. You can then see if you want to rearrange things differently.

I also updated the demo application, the README and bumped the minor version. The tests pass. I also added a `.editorconfig` file to get my editor to follow your coding style (I normally use 4 spaces).

**Comment by adonespitogo** [comment]
merged pull request #22
