### ISSUE TITLE
Size and Format validation?

### ISSUE THREAD

**Issue by fgarci03** [adonespitogo/angular-base64-upload#25]
I'm working on a file type and size validation routine that is perfomed prior to base64 conversion (I used to validate it after the ngModel was updated untill I tested a big file and it crashed my browser. Also, there's no point in performing the whole thing if it's just gonna get ditched in the end because the file is too big, for example).

Right now there are new optional attributes (max size, accepted formats and response) that handle those. The response is a string returned to the controller with the proper event description (maxSizeExceeded, invalidFormat and success - which resolves #20 I believe).

It's pretty much finished, just running some tests to be sure it's all ok (100% compatibility with how it's implemented right now). Would this be something you'd like to incorporate? Or you want it to be as simple as possible (added about 25 lines of code or so)?

**Comment by adonespitogo** [comment]
Hi sorry I was busy last few weeks. Thanks for your interest in this project. I think this is a great feature to have. Is the feature you are working on can be implemented to work on form validation like most input type?

**Comment by fgarci03** [comment]
What do you mean with the form validation?
Anyway, I forked your project and applied the changes but it I AM going to change it again and make it simpler to use.
I will let you know as soon as I have time, and if you have interest we can merge the projects again

**Comment by fgarci03** [comment]
Oh OK, I get the form validation thing. I hadn't thought about it yet, because when the validation fails, the file just doesn't get uploaded. But I will look into it and see my options. Also, am thinking of providing multiple file upload, but that will break backward compatibility. What do you think?

**Comment by adonespitogo** [comment]
I'm already working on with the multiple file selection feature. Please see [this branch](https://github.com/adonespitogo/angular-base64-upload/tree/catch-oversized-file-exception). I also have a lot of changes already. You have to merge [this branch](https://github.com/adonespitogo/angular-base64-upload/tree/catch-oversized-file-exception) to yours first before you continue to avoid conflict.

**Comment by fgarci03** [comment]
Perfect. When I have time I will merge and update my code and let you know.
Thanks!
Em 21/05/2015 23:45, "Adones Pitogo" <notifications@github.com> escreveu:

**Comment by adonespitogo** [comment]
I am also planning to include the form validation in the branch I mentioned above. Please check this branch from time to time if you can. Will let you know if I get this done maybe today and let you review my implementation. I will also look into your fork and see if I can get ideas from there.

**Comment by fgarci03** [comment]
Yes that would be cool! There are some quirks with it but (where I work) we
needed to have it readily available hence publishing without extensive
testing. I will be looking into your code and try to finish things this
weekend if I have the chance
Em 21/05/2015 23:51, "Adones Pitogo" <notifications@github.com> escreveu:
