### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by varmint09** [adonespitogo/angular-base64-upload#33]
Hello,

Versions above 0.0.6 break for me when I try to use it with npm install and then browserify the code client side, so I feel there may have been a regression somewhere?

**Comment by adonespitogo** [comment]
I see. Let me do a quick fix

**Comment by adonespitogo** [comment]
@varmint09  - please try `npm install angular-base64-upload@browserify` and let me know if it works for you, then I will merge [browserify](https://github.com/adonespitogo/angular-base64-upload/tree/browserify) to master.

**Comment by adonespitogo** [comment]
pull request #35

**Comment by varmint09** [comment]
That npm command wont work?

**Comment by adonespitogo** [comment]
try the master branch now `npm install angular-base64-upload`. `browserify` branch is merged and deleted already

**Comment by varmint09** [comment]
I get the following error; Uncaught TypeError: Cannot read property 'module' of undefined
 
and that seems to refer to this line.

var mod = window.angular.module('naif.base64', []);

I am trying to use it with this framework, and 0.0.6 was working fine with it, but obviously I want to use the most recent version of the upload encoder.

Any help welcome!

**Comment by adonespitogo** [comment]
`npm install angular-base64-upload@browserify` - that should work now. The problem was i was passing `this` to the function wrapper of my module. In the context of browser `this` = the `window` object, while in browserify it wasn't. Use this branch for now until I merge this branch to master in the next release.

**Comment by varmint09** [comment]
No compatible version found: angular-base64-upload@'browserify'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.4","0.0.5","0.0.9","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.8"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by adonespitogo** [comment]
http://stackoverflow.com/questions/16350673/depend-on-a-branch-using-a-git-url-in-a-package-json

**Comment by adonespitogo** [comment]
Please let me know if it worked.

**Comment by varmint09** [comment]
I tried npm install on the package and the full git path with #browserify appended and it wont install so i wasnt able to install the package.

**Comment by adonespitogo** [comment]
did you add it to package.json?

**Comment by varmint09** [comment]
I tried adding;

    "angular-base64-upload#browserify": "*",

**Comment by adonespitogo** [comment]
you can install the master branch and just require the minified version since it uses the window as parameter to the wrapper function of the module `require("./dist/angular-base64-upload.min.js")`
