### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by varmint09** [adonespitogo/angular-base64-upload#34]
Hello,

I would love to see an example (or support for) with compression of an image as part of the encoding process, so that might be the ability to set a maximum height/width for an image, or a ratio to reduce the "physical" dimensions by.

I feel this is going to be a common use case, so just wanted to pitch the idea!

Thanks for the library.

**Comment by adonespitogo** [comment]
I think that is quite out of scope of this project. There are a lot of image processing libraries out there already. What we can do I think is to make the base64 data of an image compatible with those image processing libraries.

**Comment by adonespitogo** [comment]
https://github.com/sloops77/AngularImageProcessor

```
app.controller('mycontroller', function ($scope, imageProcessor) {
  $scope.onloadHandler = function (e, reader, file) {
    var options = {
      resizeMaxHeight: 150,
      resizeMaxWidth: 150,
      resizeQuality: 0.7
    };

    var url = URL.createObjectURL(file)

    imageProcessor.run(url, options, function(processedImage) {
      console.log(processedImage);
    });

  };
});

<input type="file" accept="image/*" ng-model="file" onload="onloadHandler">

```

**Comment by varmint09** [comment]
That would be totally awesone, thats exactly what I have been looking for!

**Comment by ohpyupi** [comment]
I also thought of compression feature for this package. I checked the image processor you mentioned in the answer. But can I use that processor with angular-base64-upload? There are many nice features of angular-base64-upload to leave such as error handling.
