### ISSUE TITLE
Doesn't work inside ng-repeat

### ISSUE THREAD

**Issue by sadiqkhoja** [adonespitogo/angular-base64-upload#54]
When base-sixty-four-input is used inside ng-repeat and model value is predefined then model is set to null. Here is code snippet:
```
<div ng-repeat="obj in licenses">
  <label>
     <img ng-src="data:image/png;base64,{{obj.base64}}"
     <input type="file" ng-model="obj" style="display:none" base-sixty-four-input>
  </label>
</div>
```

**Comment by adonespitogo** [comment]
This should now work with the current version.

**Comment by redabakr** [comment]
Still have the same issue

**Comment by redabakr** [comment]
` <div class="row" ng-repeat="item in vm.sliderImages">
                                    <div class="col-md-2">
                                        Image {{item.Id}} url
                                    </div>
                                    <div class="col-md-8">
                                        <input type="file" name="slider1" ng-model="item" base-sixty-four-input class="form-control my-colorpicker1 colorpicker-element">
                                    </div>
                                </div>`

**Comment by redabakr** [comment]
`  <div class="row" ng-repeat="item in vm.sliderImages">`  
       ` <input type="file" name="slider1" ng-model="item.file" base-sixty-four-input ` 
            `   class="form-controly-colorpicker1 colorpicker-element">` 
   ` </div>`

**Comment by rfernand** [comment]
I have the same issue

**Comment by rfernand** [comment]
Just tried updating, and the issue now is fixed.

Thanks!

**Comment by adonespitogo** [comment]
Hello. What did you update? How was it fixed?

**Comment by rfernand** [comment]
Oh, just downloaded the last version (0.1.19) and updated the angular-base64-upload.js file.

**Comment by adonespitogo** [comment]
I see. Thanks!
