### ISSUE TITLE
Browser crash when upload large file.

### ISSUE THREAD

**Issue by GaurangGhinaiya** [adonespitogo/angular-base64-upload#58]
When i try to use lager file (>300 MB). My browser crashed. How would upload large file.

**Comment by brianmgray** [comment]
I am seeing this also. It only appears to happen when I have a handler defined onloadstart. Then uploading a 150MB file crashes the browser.

**Comment by adonespitogo** [comment]
When uploading large files, I think you shouldn't be converting it to base64 string. Aside from crashing your browsers (browsers store the base64 in-memory), it adds significant amount of overhead to file size during upload.

**Comment by adonespitogo** [comment]
I suggest using [ng-file-upload](https://github.com/danialfarid/ng-file-upload) instead for this use case.

**Comment by brianmgray** [comment]
Yeah that makes a lot of sense. This was a QA test case that we are removing for now since it is not realistic. I will check out ng-file-upload though thanks!
