### ISSUE TITLE
Clearing the input element

### ISSUE THREAD

**Issue by corehook** [adonespitogo/angular-base64-upload#66]
Hi dudes!
I have trouble with attaching file twice

``` .avatar-box.blockLeft
  .img.avatar
    / show img if file selected
    %img{'ng-src' => "data:{{user.new_avatar.filetype}};base64,{{user.new_avatar.base64}}", width: '128px', height: '128px', 'ng-if' => 'user.new_avatar'}

    / avatar input
    %input{'ng-model' => 'user.new_avatar',:accept => "image/jpeg,image/png,image/gif", :autocomplete => "off", :name => "img", :style => "cursor:pointer;", :type => "file"}(base-sixty-four-input)
  .add-file.blockLeft
    %input#avatar_browser{:accept => "image/jpeg,image/png,image/gif", :autocomplete => "off", :name => "img", :style => "cursor:pointer;", :type => "file", 'ng-model' => 'user.new_avatar'}(base-sixty-four-input)

/ Delete (clearing the input) avatar file
%p.blockLeft.file{'ng-if' => 'user.new_avatar'}
  %a{'ng-click' => 'user.new_avatar = null'}
  %span {{user.new_avatar.filename}}
```

If i chose file , then clear file handle and choose the same file angular-base64-upload do not attach againt file  to ng-model

**Comment by adonespitogo** [comment]
Hi, can you create a plunker for this? I can't reproduce it

**Comment by corehook** [comment]
yep! i will do this tomorrow

**Comment by corehook** [comment]
@adonespitogo dude i can build plunker example :-( https://plnkr.co/AioYtF2S5t0IqacSTBjP 

Module 'naif.base64' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Can you help me ?

**Comment by corehook** [comment]
why Module 'naif.base64' is not available! ?

**Comment by mmbfreitas** [comment]
I have same problem, someone can help?

**Comment by imbdb** [comment]
same here
Cant select same file again.

**Comment by RaydonZhu** [comment]
same here.

**Comment by cagrispan** [comment]
Adding 
```
elem[0].value = "";
```

after  calling the function _onAfterValidate(e); solves the problem;

```
elem.on('change', function(e) {

            if (!e.target.files.length) {
              return;
            }

            fileObjects = [];
            fileObjects = angular.copy(fileObjects);
            rawFiles = e.target.files; // use event target so we can mock the files from test
            _readFiles();
            _onChange(e);
            _onAfterValidate(e);
            elem[0].value = "";
          });
```

**Comment by adonespitogo** [comment]
@corehook Sorry been busy with work. You can't link directly to github source, it will return plain text mime type.

Sadly, I can't login to Plunker for some reason so I can't fork your example. But base on this [SO thread](http://stackoverflow.com/questions/12030686/html-input-file-selection-event-not-firing-upon-selecting-the-same-file), I can conclude @cagrispan 's solution is the right one. Let me create a quick PR for this

**Comment by garaaaid** [comment]
How i see my file?
