### ISSUE TITLE
Maximum file size

### ISSUE THREAD

**Issue by ixeldog** [adonespitogo/angular-base64-upload#72]
Is there a maximum file size? When I try and upload a file of 35MB, the browser crashes. I've narrowed it down to this code:
    for (var i = 0; i < len; i++) {
        binary += String.fromCharCode( bytes[ i ] );
    }
Is this control capable of handling large files of these sizes?

**Comment by adonespitogo** [comment]
It depends on the amount of RAM you have. This directive is not supposed to be used for large files.

**Comment by adonespitogo** [comment]
There is an option `do-not-parse-if-oversize` that prevents parsing large files to avoid browser crash:

```
<form name="form">
  <input type="file" ng-model="files" name="files" base-sixty-four-input do-not-parse-if-oversize>
</form>
```
